# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7ccccc85e671e5ce360462005f597883385f0a601b2779b9af0bd6c7c4433dde14bd1c6d746e5a9d1a1ee5ce9adaaeed5fd2ffdb2e4cae70c7a3d78789f1147

test:
  secret_key_base: 6d49268def4454505debb95ba69b06c9c919cfcc9030701c987624eca1363e9cd0c68542fe779a1de1294022821ac4d5e1c7b1b808352cdc9bbb22af5ce5287e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
